version: '3.10'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./assets/sql/create_db.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - ./assets/sql/fill_in_db.sql:/docker-entrypoint-initdb.d/fill_tables.sql
  app:
    build: .
    env_file:
    - dev/.env